//
//  StoriesView.swift
//  VoiceAI
//
//  Created by MACBOOK PRO on 24/04/24.
//

import SwiftUI

struct StoriesView: View {
    
    @State private var selectedTopic: Topics = .persahabatan
    @State private var selectedMood: Mood = .bahagia
    @State private var todayStory: String = ""
    
    var body: some View {
        NavigationStack {
            Form {
                // picker view
                Section {
                    Picker(selection: $selectedTopic, content: {
                        ForEach(Topics.allCases, id:\.self) { topic in
                            Text(topic.rawValue.capitalized)
                                .font(.subheadline)
                                .fontWeight(.bold)
                                .tag(topic)
                        }
                    }, label: {
                        Text("Choose topic")
                            .foregroundStyle(.gray)
                            .padding(.vertical, 8)
                    })
                    .tint(.primary)
                    
                    Picker(selection: $selectedMood, content: {
                        ForEach(Mood.allCases, id: \.self) { mood in
                            Text(mood.rawValue.capitalized)
                                .font(.subheadline)
                                .fontWeight(.bold)
                                .tag(mood)
                        }
                    }, label: {
                        Text("Choose mood")
                            .foregroundStyle(.gray)
                            .padding(.vertical, 8)
                    })
                    .tint(.primary)
                } header: {
                    Text("Topics")
                } footer: {
                    Text("Choose any topics and mood that you want to listen.")
                }
                .fontWeight(.bold)
                
                // text editor
                Section(content: {
                    TextEditor(text: $todayStory)
                        .frame(height: 200)
                        .font(.system(.headline, design: .rounded))
                        .foregroundStyle(.blue)
                }, header: {
                    Text("Todays Story")
                }, footer: {
                    Text("This stories are generated by Gemini AI")
                })
                .fontWeight(.bold)
                
                // button generate
                Button(action: {
                    
                }, label: {
                    Text("GENERATE")
                        .font(.system(.callout, design: .rounded))
                        .fontWeight(.bold)
                        .tint(.primary)
                })
                .buttonStyle(.plain)
                .frame(minWidth: 0, maxWidth: .infinity)

            }
            .navigationTitle("Stories")
        }
    }
}

#Preview {
    StoriesView()
}
